name: Build PR & check title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  check-title:
    name: Conventional commit validation on PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build PR
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn build
