name: Build Docker

on:
  push:
    branches:
      - "v2-*"
      - "!v2-develop"
      - "!v2-main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        id: download
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "prop=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - run: echo "Current branch ${{steps.extract_branch.outputs.prop}}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: inseefr/public-enemy
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{steps.extract_branch.outputs.prop}}
